# Generated by Django 3.0.5 on 2021-04-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('percentage', models.FloatField()),
                ('loan_amt_min', models.FloatField()),
                ('loan_amt_max', models.FloatField()),
                ('status', models.BinaryField(blank=True, default=True, null=True)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
