# Generated by Django 3.0.5 on 2021-01-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.BinaryField(default=True),
            preserve_default=False,
        ),
    ]
