# Generated by Django 3.0.5 on 2021-01-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_auto_20210127_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='status',
            field=models.BinaryField(blank=True, default=True, null=True),
        ),
    ]
