# Generated by Django 3.0.5 on 2021-04-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('amt_collected', models.FloatField()),
                ('interest', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan.Loan')),
            ],
        ),
    ]
