# Generated by Django 3.0.5 on 2021-02-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20210127_0240'),
        ('releaseLoan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseloan',
            name='loan_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan.Loan'),
        ),
    ]
