# Generated by Django 3.0.5 on 2021-03-17 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20210317_0558'),
        ('releaseLoan', '0002_auto_20210209_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseloan',
            name='loan_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan.Loan'),
        ),
    ]
