# Generated by Django 3.0.5 on 2021-04-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('amt', models.FloatField()),
                ('isCredit', models.BinaryField()),
                ('balance', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
