# Generated by Django 3.0.5 on 2021-01-21 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('loan_no', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('loan_amt', models.FloatField()),
                ('totalDue', models.FloatField()),
                ('qty', models.IntegerField()),
                ('itemList', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('loan_date', models.DateField()),
                ('misc_charges', models.FloatField()),
                ('gross_wt', models.FloatField()),
                ('net_wt', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
