# Generated by Django 3.0.5 on 2021-04-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=6, unique=True)),
                ('loan_amt', models.FloatField()),
                ('totalDue', models.FloatField()),
                ('qty', models.IntegerField()),
                ('itemList', models.CharField(max_length=200)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('loan_date', models.DateField(auto_now_add=True, null=True)),
                ('misc_charges', models.FloatField(blank=True, null=True)),
                ('gross_wt', models.FloatField(blank=True, null=True)),
                ('net_wt', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
