# Generated by Django 3.0.5 on 2021-03-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20210127_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
